### ISSUE TITLE
Does not automatically resolve numy dependency

### ISSUE THREAD

**Issue by igordertigor** [TwentyBN/pyfackel#1]
Using `pip install pyfackel` will download the pytorch binaries, but does not install numpy, so we get the following error message:
```
$ python -c 'import torch'
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cirrascale/pyfackel/lib/python3.5/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import
```
Which is resolved by `pip install numpy`.

**Comment by guillaumebrg** [comment]
PR #2 should solve this (pip install torchvision does install numpy as well).
